name: Github Actions FGC
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]    
    
jobs:
  build:
    name: ğŸ”¨ Build da aplicaÃ§Ã£o
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do cÃ³digo
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: ğŸ”§ Restaurar e compilar soluÃ§Ã£o
      run: dotnet build Payments.Microservice.API/Payments.Microservice.API.sln  --configuration Release
      
  test:
    name: âœ… Testes UnitÃ¡rios
    runs-on: ubuntu-latest
    needs: build  # depende do job de build

    steps:
    - name:  Checkout do cÃ³digo
      uses: actions/checkout@v4

    - name: Instalar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x'

    - name: Executar testes
      run: |
        dotnet test Payments.Microservice.Tests/Payments.Microservice.Tests.csproj --configuration Debug --verbosity normal
        
  push:
    name: ğŸš€ Docker Build & Push
    runs-on: ubuntu-latest
    needs: test  # depende do job de test

    steps:
    - name: ğŸ“¥ Checkout do cÃ³digo
      uses: actions/checkout@v4

    - name: ğŸ§ª Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  
    - name: ğŸ” Login no Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
  
    - name: ğŸ³ Build e Push da imagem para ECR
      uses: docker/build-push-action@v5
      with:
          context: .
          push: true
          tags: 626547610206.dkr.ecr.us-east-1.amazonaws.com/payments-microservice:latest
